'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SMM2VIEWER.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  重写当前线程的 CurrentUICulture 属性，对
        '''  使用此强类型资源类的所有资源查找执行重写。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Cmn_BackBtn_00__Cmn_BackBtn_00_Icon_MenuNwk_01_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cmn_BackBtn_00--Cmn_BackBtn_00-Icon_MenuNwk_01^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Cmn_EventClearMark_00__Cmn_EventClearMark_00_EventClearListIcon_00_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cmn_EventClearMark_00--Cmn_EventClearMark_00-EventClearListIcon_00^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Cmn_EventClearTime_00__Cmn_EventClearTime_00_NCL_IconS32_BestTime_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cmn_EventClearTime_00--Cmn_EventClearTime_00-NCL_IconS32_BestTime^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Cmn_GoodBtn_00__Cmn_GoodBtn_00_Heart_00_d() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cmn_GoodBtn_00--Cmn_GoodBtn_00-Heart_00^d", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Cmn_InfoRealTime_00__Cmn_InfoRealTime_00_Icon_Comment_00_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cmn_InfoRealTime_00--Cmn_InfoRealTime_00-Icon_Comment_00^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Cmn_InfoRealTime_00__Cmn_InfoRealTime_00_Icon_MenuNwk_01_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cmn_InfoRealTime_00--Cmn_InfoRealTime_00-Icon_MenuNwk_01^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Cmn_InfoRealTime_00__Cmn_InfoRealTime_00_NCL_IconS_BestTime_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cmn_InfoRealTime_00--Cmn_InfoRealTime_00-NCL_IconS_BestTime^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Cmn_InfoRealTime_00__Cmn_InfoRealTime_00_NCL_IconS_Footprint_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cmn_InfoRealTime_00--Cmn_InfoRealTime_00-NCL_IconS_Footprint^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Cmn_InfoRealTime_00__Cmn_InfoRealTime_00_NCL_IconS_Good_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cmn_InfoRealTime_00--Cmn_InfoRealTime_00-NCL_IconS_Good^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Cmn_Mission_00__Cmn_Mission_00_Icon_EditBtn_01_u() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cmn_Mission_00--Cmn_Mission_00-Icon_EditBtn_01^u", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Cmn_NegativeBtn_00__Cmn_NegativeBtn_00_HeartBreak_00_d() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cmn_NegativeBtn_00--Cmn_NegativeBtn_00-HeartBreak_00^d", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Cmn_NegativeBtn_00__Cmn_NegativeBtn_00_HeartBreak_01_d() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cmn_NegativeBtn_00--Cmn_NegativeBtn_00-HeartBreak_01^d", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Cmn_PauseMenu_00__Cmn_PauseMenu_00_NCL_IconS_PersonalBest_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cmn_PauseMenu_00--Cmn_PauseMenu_00-NCL_IconS_PersonalBest^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Cmn_PauseMenu_00__Cmn_PauseMenu_00_NCL_IconS32_BestTime_d() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cmn_PauseMenu_00--Cmn_PauseMenu_00-NCL_IconS32_BestTime^d", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Cmn_PauseMenu_00__Cmn_PauseMenu_00_NCL_TitleIcon_03_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cmn_PauseMenu_00--Cmn_PauseMenu_00-NCL_TitleIcon_03^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Cmn_PauseMenu_00__Cmn_PauseMenu_00_TagIcon_00_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cmn_PauseMenu_00--Cmn_PauseMenu_00-TagIcon_00^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Cmn_SubBtnS_00__Cmn_SubBtnS_00_Icon_MenuTitleBtn_00_d() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cmn_SubBtnS_00--Cmn_SubBtnS_00-Icon_MenuTitleBtn_00^d", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Edit_AreaBtn_00__Edit_AreaBtn_00_Icon_Area_00_q() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit_AreaBtn_00--Edit_AreaBtn_00-Icon_Area_00^q", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Edit_AreaBtn_00__Edit_AreaBtn_00_Icon_Area_01_q() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit_AreaBtn_00--Edit_AreaBtn_00-Icon_Area_01^q", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Edit_AreaBtn_00__Edit_AreaBtn_00_Icon_Veritical_00_t() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit_AreaBtn_00--Edit_AreaBtn_00-Icon_Veritical_00^t", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Edit_AreaBtn_00__Edit_AreaBtn_00_Icon_Veritical_01_t() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit_AreaBtn_00--Edit_AreaBtn_00-Icon_Veritical_01^t", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Edit_ChangeHourBtn_00__Edit_ChangeHourBtn_00_EditBtn_SunBtn_00_u() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit_ChangeHourBtn_00--Edit_ChangeHourBtn_00-EditBtn_SunBtn_00^u", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Edit_ChangeHourBtn_00__Edit_ChangeHourBtn_00_EditBtn_SunBtn_01_u() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit_ChangeHourBtn_00--Edit_ChangeHourBtn_00-EditBtn_SunBtn_01^u", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Edit_ModeGuide_00__Edit_ModeGuide_00_Icon_LayerIcon_00_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit_ModeGuide_00--Edit_ModeGuide_00-Icon_LayerIcon_00^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Edit_ModeGuide_00__Edit_ModeGuide_00_Icon_LayerIcon_01_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit_ModeGuide_00--Edit_ModeGuide_00-Icon_LayerIcon_01^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Edit_ModeGuide_00__Edit_ModeGuide_00_Icon_LayerIcon_02_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit_ModeGuide_00--Edit_ModeGuide_00-Icon_LayerIcon_02^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Edit_ModeGuide_00__Edit_ModeGuide_00_Icon_LayerIcon_03_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit_ModeGuide_00--Edit_ModeGuide_00-Icon_LayerIcon_03^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Edit_NoAutoScrollBtn_00__Edit_NoAutoScrollBtn_00_Icon_Scroll_00_u() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit_NoAutoScrollBtn_00--Edit_NoAutoScrollBtn_00-Icon_Scroll_00^u", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Edit_RingCategory_00__Edit_RingCategory_00_CategoryIcon_00_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit_RingCategory_00--Edit_RingCategory_00-CategoryIcon_00^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Edit_RingCategory_00__Edit_RingCategory_00_CategoryIcon_01_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit_RingCategory_00--Edit_RingCategory_00-CategoryIcon_01^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Edit_RingCategory_00__Edit_RingCategory_00_CategoryIcon_02_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit_RingCategory_00--Edit_RingCategory_00-CategoryIcon_02^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Edit_RingCategory_00__Edit_RingCategory_00_CategoryIcon_03_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit_RingCategory_00--Edit_RingCategory_00-CategoryIcon_03^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Edit_RingCategory_01__Edit_RingCategory_01_CategoryIcon_04_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit_RingCategory_01--Edit_RingCategory_01-CategoryIcon_04^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Edit_RingCategory_01__Edit_RingCategory_01_CategoryIcon_05_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit_RingCategory_01--Edit_RingCategory_01-CategoryIcon_05^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Edit_RingCategory_01__Edit_RingCategory_01_CategoryIcon_06_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit_RingCategory_01--Edit_RingCategory_01-CategoryIcon_06^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Edit_RingCategory_01__Edit_RingCategory_01_CategoryIcon_07_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit_RingCategory_01--Edit_RingCategory_01-CategoryIcon_07^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Edit_RingCategory_01__Edit_RingCategory_01_CategoryIcon_08_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit_RingCategory_01--Edit_RingCategory_01-CategoryIcon_08^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Edit_ScrollEditBtn_00__Edit_ScrollEditBtn_00_EditBtn_LayerIconS_00_u() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit_ScrollEditBtn_00--Edit_ScrollEditBtn_00-EditBtn_LayerIconS_00^u", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Edit_SoundBtn_00__Edit_SoundBtn_00_Icon_Edit_00_u() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit_SoundBtn_00--Edit_SoundBtn_00-Icon_Edit_00^u", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Edit_SoundBtn_00__Edit_SoundBtn_00_Icon_Edit_03_u() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit_SoundBtn_00--Edit_SoundBtn_00-Icon_Edit_03^u", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Edit_TimerBtn_00__Edit_TimerBtn_00_Icon_EditBtn_00_u() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit_TimerBtn_00--Edit_TimerBtn_00-Icon_EditBtn_00^u", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Edit_TrashCan_00__Edit_TrashCan_00_Icon_Trashcan_00_u() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit_TrashCan_00--Edit_TrashCan_00-Icon_Trashcan_00^u", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Edit_TrashCan_00__Edit_TrashCan_00_Icon_Trashcan_01_u() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit_TrashCan_00--Edit_TrashCan_00-Icon_Trashcan_01^u", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Edit_WaterLevelBtn_00__Edit_WaterLevelBtn_00_Icon_Edit_05_u() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit_WaterLevelBtn_00--Edit_WaterLevelBtn_00-Icon_Edit_05^u", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Edit_WaterLevelBtn_00__Edit_WaterLevelBtn_00_Icon_Edit_12_u() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit_WaterLevelBtn_00--Edit_WaterLevelBtn_00-Icon_Edit_12^u", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Edit_WaterLevelBtn_00__Edit_WaterLevelBtn_00_Icon_Edit_14_u() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit_WaterLevelBtn_00--Edit_WaterLevelBtn_00-Icon_Edit_14^u", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Lcl_CourseInfoWindow_00__Lcl_CourseInfoWindow_00_CoopModeIcon_u() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lcl_CourseInfoWindow_00--Lcl_CourseInfoWindow_00-CoopModeIcon^u", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Lcl_CourseInfoWindow_00__Lcl_CourseInfoWindow_00_NCL_ClearCheck32_00_d() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lcl_CourseInfoWindow_00--Lcl_CourseInfoWindow_00-NCL_ClearCheck32_00^d", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Lcl_CourseInfoWindow_00__Lcl_CourseInfoWindow_00_NCL_IconS_Footprint_d() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lcl_CourseInfoWindow_00--Lcl_CourseInfoWindow_00-NCL_IconS_Footprint^d", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Lcl_CourseInfoWindow_00__Lcl_CourseInfoWindow_00_NCL_IconS_Good_d() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lcl_CourseInfoWindow_00--Lcl_CourseInfoWindow_00-NCL_IconS_Good^d", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Lcl_CourseInfoWindow_00__Lcl_CourseInfoWindow_00_TagIcon_00_d() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lcl_CourseInfoWindow_00--Lcl_CourseInfoWindow_00-TagIcon_00^d", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Lcl_DecideBtnI_00__Lcl_DecideBtnI_00_NameIcon_00_d() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lcl_DecideBtnI_00--Lcl_DecideBtnI_00-NameIcon_00^d", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property MyW_Ending_00__MyW_Ending_00_MyW_Ster_00_d() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MyW_Ending_00--MyW_Ending_00-MyW_Ster_00^d", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property MyW_Ending_00__MyW_Ending_00_NCL_ClearCheck64_00_u() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MyW_Ending_00--MyW_Ending_00-NCL_ClearCheck64_00^u", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_ClearCheck_00__Nwk_ClearCheck_00_NCL_ListIconClearF_00_l() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_ClearCheck_00--Nwk_ClearCheck_00-NCL_ListIconClearF_00^l", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_CommentDrawing_00__Nwk_CommentDrawing_00_CommentPostPen_00_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_CommentDrawing_00--Nwk_CommentDrawing_00-CommentPostPen_00^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_CommentPosting_00__Nwk_CommentPosting_00_CommentPostDrawing_00_t() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_CommentPosting_00--Nwk_CommentPosting_00-CommentPostDrawing_00^t", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_CommentPosting_00__Nwk_CommentPosting_00_CommentPostStamp_00_t() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_CommentPosting_00--Nwk_CommentPosting_00-CommentPostStamp_00^t", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_CommentPosting_00__Nwk_CommentPosting_00_EmotionIconFrustrated_00_t() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_CommentPosting_00--Nwk_CommentPosting_00-EmotionIconFrustrated_00^t", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_CommentPosting_00__Nwk_CommentPosting_00_EmotionIconHappy_00_t() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_CommentPosting_00--Nwk_CommentPosting_00-EmotionIconHappy_00^t", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_CommentPosting_00__Nwk_CommentPosting_00_EmotionIconLike_00_t() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_CommentPosting_00--Nwk_CommentPosting_00-EmotionIconLike_00^t", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_CommentPosting_00__Nwk_CommentPosting_00_EmotionIconNormal_00_t() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_CommentPosting_00--Nwk_CommentPosting_00-EmotionIconNormal_00^t", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_CommentPosting_00__Nwk_CommentPosting_00_EmotionIconPuzzled_00_t() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_CommentPosting_00--Nwk_CommentPosting_00-EmotionIconPuzzled_00^t", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_CommentPosting_00__Nwk_CommentPosting_00_EmotionIconSurprised_00_t() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_CommentPosting_00--Nwk_CommentPosting_00-EmotionIconSurprised_00^t", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_CourseDetail_00__Nwk_CourseDetail_00_NCL_IconS_Footprint_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_CourseDetail_00--Nwk_CourseDetail_00-NCL_IconS_Footprint^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_CourseDetail_00__Nwk_CourseDetail_00_NCL_IconS_Good_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_CourseDetail_00--Nwk_CourseDetail_00-NCL_IconS_Good^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_CourseList_00__Nwk_CourseList_00_NCL_IconS_BestTime_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_CourseList_00--Nwk_CourseList_00-NCL_IconS_BestTime^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_CourseList_00__Nwk_CourseList_00_NCL_IconS_ClearFirst_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_CourseList_00--Nwk_CourseList_00-NCL_IconS_ClearFirst^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_CourseListMaker_00__Nwk_CourseListMaker_00_FriendIcon_00_t() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_CourseListMaker_00--Nwk_CourseListMaker_00-FriendIcon_00^t", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_CourseListMaker_00__Nwk_CourseListMaker_00_NCL_TitleIcon_01_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_CourseListMaker_00--Nwk_CourseListMaker_00-NCL_TitleIcon_01^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_CourseListMaker_00__Nwk_CourseListMaker_00_OfficialUserIcon_t() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_CourseListMaker_00--Nwk_CourseListMaker_00-OfficialUserIcon^t", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_CourseListWindow_00__Nwk_CourseListWindow_00_TagIcon_00_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_CourseListWindow_00--Nwk_CourseListWindow_00-TagIcon_00^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_DownloadPlayBtn_00__Nwk_DownloadPlayBtn_00_PlayBtnIconDownload_00_u() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_DownloadPlayBtn_00--Nwk_DownloadPlayBtn_00-PlayBtnIconDownload_00^u", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_DpointBtn_00__Nwk_DpointBtn_00_Icon_DpointBtn_00_u() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_DpointBtn_00--Nwk_DpointBtn_00-Icon_DpointBtn_00^u", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_DressTabBtn_00__Nwk_DressTabBtn_00_DressIcon_00_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_DressTabBtn_00--Nwk_DressTabBtn_00-DressIcon_00^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_DressUp_00__Nwk_DressUp_00_DressIcon_01_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_DressUp_00--Nwk_DressUp_00-DressIcon_01^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_DressUp_00__Nwk_DressUp_00_DressIcon_02_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_DressUp_00--Nwk_DressUp_00-DressIcon_02^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_DressUp_00__Nwk_DressUp_00_DressIcon_03_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_DressUp_00--Nwk_DressUp_00-DressIcon_03^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_DressUp_00__Nwk_DressUp_00_DressIcon_04_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_DressUp_00--Nwk_DressUp_00-DressIcon_04^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_EndlessModeMenu_00__Nwk_EndlessModeMenu_00_NCL_TitleIcon_03_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_EndlessModeMenu_00--Nwk_EndlessModeMenu_00-NCL_TitleIcon_03^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_EventClearListBtn_00__Nwk_EventClearListBtn_00_EventClearListIcon_00_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_EventClearListBtn_00--Nwk_EventClearListBtn_00-EventClearListIcon_00^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_EventCourseData_00__Nwk_EventCourseData_00_NCL_IconS_PersonalBest_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_EventCourseData_00--Nwk_EventCourseData_00-NCL_IconS_PersonalBest^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_RoomSituation_00__Nwk_RoomSituation_00_BtlModeIcon_00_d() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_RoomSituation_00--Nwk_RoomSituation_00-BtlModeIcon_00^d", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_RoomSituation_00__Nwk_RoomSituation_00_BtlModeIcon_01_d() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_RoomSituation_00--Nwk_RoomSituation_00-BtlModeIcon_01^d", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_RoomSituation_00__Nwk_RoomSituation_00_LockIcon_01_t() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_RoomSituation_00--Nwk_RoomSituation_00-LockIcon_01^t", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_RoomSituation_00__Nwk_RoomSituation_00_MainFrame_00_d() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_RoomSituation_00--Nwk_RoomSituation_00-MainFrame_00^d", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_SignalLevel_00__Nwk_SignalLevel_00_BalloonPoint_00_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_SignalLevel_00--Nwk_SignalLevel_00-BalloonPoint_00^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_SignalLevel_00__Nwk_SignalLevel_00_MainFrameS_00_d() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_SignalLevel_00--Nwk_SignalLevel_00-MainFrameS_00^d", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_SortBtn_00__Nwk_SortBtn_00_BtnMain_00_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_SortBtn_00--Nwk_SortBtn_00-BtnMain_00^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_SortBtn_00__Nwk_SortBtn_00_BtnMainShB_00_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_SortBtn_00--Nwk_SortBtn_00-BtnMainShB_00^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_SortBtn_00__Nwk_SortBtn_00_BtnMainShT_00_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_SortBtn_00--Nwk_SortBtn_00-BtnMainShT_00^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_SortBtn_00__Nwk_SortBtn_00_ClearCourseIconBestTime_00_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_SortBtn_00--Nwk_SortBtn_00-ClearCourseIconBestTime_00^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_SortBtn_00__Nwk_SortBtn_00_ClearCourseIconClear_00_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_SortBtn_00--Nwk_SortBtn_00-ClearCourseIconClear_00^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_SortBtn_00__Nwk_SortBtn_00_ClearCourseIconClearFirst_00_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_SortBtn_00--Nwk_SortBtn_00-ClearCourseIconClearFirst_00^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_SortBtn_00__Nwk_SortBtn_00_ClearCourseIconMCEasy_00_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_SortBtn_00--Nwk_SortBtn_00-ClearCourseIconMCEasy_00^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_SortBtn_00__Nwk_SortBtn_00_ClearCourseIconMCHard_00_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_SortBtn_00--Nwk_SortBtn_00-ClearCourseIconMCHard_00^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_SortBtn_00__Nwk_SortBtn_00_ClearCourseIconMCNormal_00_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_SortBtn_00--Nwk_SortBtn_00-ClearCourseIconMCNormal_00^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_SortBtn_00__Nwk_SortBtn_00_ClearCourseIconMCVeryHard_00_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_SortBtn_00--Nwk_SortBtn_00-ClearCourseIconMCVeryHard_00^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_SortBtn_00__Nwk_SortBtn_00_NCL_BtnIconSearch_00_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_SortBtn_00--Nwk_SortBtn_00-NCL_BtnIconSearch_00^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_SortBtn_00__Nwk_SortBtn_00_NCL_SortBattlePoints_00_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_SortBtn_00--Nwk_SortBtn_00-NCL_SortBattlePoints_00^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_SortBtn_00__Nwk_SortBtn_00_NCL_SortClear_00_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_SortBtn_00--Nwk_SortBtn_00-NCL_SortClear_00^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_SortBtn_00__Nwk_SortBtn_00_NCL_SortCoursePoints_00_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_SortBtn_00--Nwk_SortBtn_00-NCL_SortCoursePoints_00^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_SortBtn_00__Nwk_SortBtn_00_NCL_SortTotal_00_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_SortBtn_00--Nwk_SortBtn_00-NCL_SortTotal_00^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_SortBtn_00__Nwk_SortBtn_00_NCL_SortWeekly_00_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_SortBtn_00--Nwk_SortBtn_00-NCL_SortWeekly_00^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_SortBtn_01__Nwk_SortBtn_01_ClearCourseIconBestTime_00_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_SortBtn_01--Nwk_SortBtn_01-ClearCourseIconBestTime_00^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_SortBtn_01__Nwk_SortBtn_01_ClearCourseIconClear_00_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_SortBtn_01--Nwk_SortBtn_01-ClearCourseIconClear_00^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_SortBtn_01__Nwk_SortBtn_01_ClearCourseIconClearFirst_00_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_SortBtn_01--Nwk_SortBtn_01-ClearCourseIconClearFirst_00^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_SortBtn_01__Nwk_SortBtn_01_ClearCourseIconMCEasy_00_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_SortBtn_01--Nwk_SortBtn_01-ClearCourseIconMCEasy_00^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_SortBtn_01__Nwk_SortBtn_01_ClearCourseIconMCHard_00_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_SortBtn_01--Nwk_SortBtn_01-ClearCourseIconMCHard_00^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_SortBtn_01__Nwk_SortBtn_01_ClearCourseIconMCNormal_00_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_SortBtn_01--Nwk_SortBtn_01-ClearCourseIconMCNormal_00^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_SortBtn_01__Nwk_SortBtn_01_ClearCourseIconMCVeryHard_00_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_SortBtn_01--Nwk_SortBtn_01-ClearCourseIconMCVeryHard_00^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_SortBtn_01__Nwk_SortBtn_01_NCL_BtnIconSearch_00_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_SortBtn_01--Nwk_SortBtn_01-NCL_BtnIconSearch_00^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_SortBtn_01__Nwk_SortBtn_01_NCL_SortBattlePoints_00_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_SortBtn_01--Nwk_SortBtn_01-NCL_SortBattlePoints_00^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_SortBtn_01__Nwk_SortBtn_01_NCL_SortClear_00_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_SortBtn_01--Nwk_SortBtn_01-NCL_SortClear_00^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_SortBtn_01__Nwk_SortBtn_01_NCL_SortCoursePoints_00_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_SortBtn_01--Nwk_SortBtn_01-NCL_SortCoursePoints_00^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_SortBtn_01__Nwk_SortBtn_01_NCL_SortTotal_00_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_SortBtn_01--Nwk_SortBtn_01-NCL_SortTotal_00^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_SortBtn_01__Nwk_SortBtn_01_NCL_SortWeekly_00_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_SortBtn_01--Nwk_SortBtn_01-NCL_SortWeekly_00^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_SortWindow_00__Nwk_SortWindow_00_NCL_SortClear_00_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_SortWindow_00--Nwk_SortWindow_00-NCL_SortClear_00^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_SortWindow_00__Nwk_SortWindow_00_NCL_SortCoursePoints_00_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_SortWindow_00--Nwk_SortWindow_00-NCL_SortCoursePoints_00^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_SortWindow_00__Nwk_SortWindow_00_NCL_SortTotal_00_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_SortWindow_00--Nwk_SortWindow_00-NCL_SortTotal_00^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_SortWindow_00__Nwk_SortWindow_00_NCL_SortWeekly_00_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_SortWindow_00--Nwk_SortWindow_00-NCL_SortWeekly_00^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_StampFilterBtn_00__Nwk_StampFilterBtn_00_CommentPostStamp_00_t() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_StampFilterBtn_00--Nwk_StampFilterBtn_00-CommentPostStamp_00^t", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_TagRegister_00__Nwk_TagRegister_00_TagIcon_00_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_TagRegister_00--Nwk_TagRegister_00-TagIcon_00^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_TitleBtn_00__Nwk_TitleBtn_00_NCL_TitleIcon_00_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_TitleBtn_00--Nwk_TitleBtn_00-NCL_TitleIcon_00^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_TitleBtn_01__Nwk_TitleBtn_01_NCL_TitleIcon_01_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_TitleBtn_01--Nwk_TitleBtn_01-NCL_TitleIcon_01^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_TitleBtn_02__Nwk_TitleBtn_02_NCL_TitleIcon_02_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_TitleBtn_02--Nwk_TitleBtn_02-NCL_TitleIcon_02^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_UploadCheck_00__Nwk_UploadCheck_00_Icon_Upload_00_u() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_UploadCheck_00--Nwk_UploadCheck_00-Icon_Upload_00^u", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_UploadCheck_00__Nwk_UploadCheck_00_Icon_Upload_01_u() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_UploadCheck_00--Nwk_UploadCheck_00-Icon_Upload_01^u", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_VoiseBtn_00__Nwk_VoiseBtn_00_VoiseIcon_00_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_VoiseBtn_00--Nwk_VoiseBtn_00-VoiseIcon_00^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_VoiseBtn_00__Nwk_VoiseBtn_00_VoiseIcon_01_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_VoiseBtn_00--Nwk_VoiseBtn_00-VoiseIcon_01^s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_WorldMapInfo_00__Nwk_WorldMapInfo_00_WM_GameSkin_airship_00_l() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_WorldMapInfo_00--Nwk_WorldMapInfo_00-WM_GameSkin_airship_00^l", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_WorldMapInfo_00__Nwk_WorldMapInfo_00_WM_GameSkin_athletic_00_l() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_WorldMapInfo_00--Nwk_WorldMapInfo_00-WM_GameSkin_athletic_00^l", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_WorldMapInfo_00__Nwk_WorldMapInfo_00_WM_GameSkin_castle_00_l() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_WorldMapInfo_00--Nwk_WorldMapInfo_00-WM_GameSkin_castle_00^l", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_WorldMapInfo_00__Nwk_WorldMapInfo_00_WM_GameSkin_desert_00_l() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_WorldMapInfo_00--Nwk_WorldMapInfo_00-WM_GameSkin_desert_00^l", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_WorldMapInfo_00__Nwk_WorldMapInfo_00_WM_GameSkin_hauntedhouse_00_l() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_WorldMapInfo_00--Nwk_WorldMapInfo_00-WM_GameSkin_hauntedhouse_00^l", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_WorldMapInfo_00__Nwk_WorldMapInfo_00_WM_GameSkin_plain_00_l() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_WorldMapInfo_00--Nwk_WorldMapInfo_00-WM_GameSkin_plain_00^l", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_WorldMapInfo_00__Nwk_WorldMapInfo_00_WM_GameSkin_snow_00_l() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_WorldMapInfo_00--Nwk_WorldMapInfo_00-WM_GameSkin_snow_00^l", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_WorldMapInfo_00__Nwk_WorldMapInfo_00_WM_GameSkin_underground_00_l() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_WorldMapInfo_00--Nwk_WorldMapInfo_00-WM_GameSkin_underground_00^l", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_WorldMapInfo_00__Nwk_WorldMapInfo_00_WM_GameSkin_water_00_l() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_WorldMapInfo_00--Nwk_WorldMapInfo_00-WM_GameSkin_water_00^l", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Nwk_WorldMapInfo_00__Nwk_WorldMapInfo_00_WM_GameSkin_woods_00_l() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nwk_WorldMapInfo_00--Nwk_WorldMapInfo_00-WM_GameSkin_woods_00^l", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Play_Comment_00__Play_Comment_00_MCB_FukidashiIcon_00_t() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Play_Comment_00--Play_Comment_00-MCB_FukidashiIcon_00^t", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Play_PlaySceneBattle_00__Play_PlaySceneBattle_00_RespawnPointMiddle_00_u() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Play_PlaySceneBattle_00--Play_PlaySceneBattle_00-RespawnPointMiddle_00^u", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Play_PlaySceneBattle_00__Play_PlaySceneBattle_00_RespawnPointStart_00_u() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Play_PlaySceneBattle_00--Play_PlaySceneBattle_00-RespawnPointStart_00^u", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Qst_Reward_00__Qst_Reward_00_RewordIcon_02_u() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Qst_Reward_00--Qst_Reward_00-RewordIcon_02^u", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
